name: Deploy Cluster

on:
  push:
    paths:
      - 'cluster-creation/**'
      - 'cluster-installation/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Initialize Terraform for Cluster Creation
      working-directory: ./cluster-creation/dev
      run: terraform init

    - name: Apply Terraform for Cluster Creation
      working-directory: ./cluster-creation/dev
      run: terraform apply -auto-approve -var "aws_region=${{ env.AWS_REGION }}"

    - name: Initialize Terraform for Cluster Installation
      working-directory: ./cluster-installation/dev
      run: terraform init

    - name: Apply Terraform for Cluster Installation
      working-directory: ./cluster-installation/dev
      run: terraform apply -auto-approve -var "aws_region=${{ env.AWS_REGION }}"
