name: 'Terraform Application Creation'
description: 'Initialize and apply Terraform configuration for application deployment'

inputs:
  awsAccessKeyId:
    description: 'AWS Access Key ID'
    required: true
  awsBucket:
    description: 'AWS Bucket name'
    required: true
  awsDynamoDBTable:
    description: 'AWS DynamoDB Table name'
    required: true
  awsRegion:
    description: 'AWS S3 Region'
    required: true
  awsSecretAccessKey:
    description: 'AWS Secret Access Key'
    required: true
  branch:
    description: 'Branch for the infrastructure'
    required: true
  environment:
    description: 'Environment for the infrastructure'
    required: true
  kubeconfigPath:
    description: 'Kubeconfig file path'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=${{ inputs.awsBucket }}" \
          -backend-config="key=${{ env.BACKEND_KEY }}" \
          -backend-config="region=${{ inputs.awsRegion }}" \
          -backend-config="dynamodb_table=${{ inputs.awsDynamoDBTable }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.awsAccessKeyId }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.awsSecretAccessKey }}
        BACKEND_KEY: "gitops-demo/${{ inputs.environment }}/${{ inputs.branch }}/application-key.tfstate"
      working-directory: terraform/applications/${{ inputs.environment }}
      shell: bash

    - name: Terraform Apply
      run: |
        terraform apply \
          -auto-approve \
          -var "kubeconfig_path=${{ inputs.kubeconfigPath }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.awsAccessKeyId }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.awsSecretAccessKey }}
      working-directory: terraform/applications/${{ inputs.environment }}
      shell: bash