name: 'Terraform Cluster Destroy'
description: 'Destroy Terraform configuration for cluster'

inputs:
  clusterName:
    description: 'Cluster name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=${{ vars.AWS_BUCKET }}" \
          -backend-config="key=${{ env.BACKEND_KEY }}" \
          -backend-config="region=${{ vars.AWS_REGION }}" \
          -backend-config="dynamodb_table=${{ vars.AWS_DYNAMODB_TABLE }}"
      env:
        BACKEND_KEY: "gitops-demo/${{ github.environment }}/${{ github.ref_name }}/cluster.tfstate"
      working-directory: terraform/cluster-creation/${{ github.environment }}
      shell: bash

    - name: Terraform Destroy
      run: |
        terraform destroy \
          -auto-approve \
          -var="cluster_name=${{ inputs.clusterName }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      working-directory: terraform/cluster-creation/${{ github.environment }}
      shell: bash
