name: 'Terraform Cluster Destroy'
description: 'Destroy Terraform configuration for cluster'

inputs:
  awsAccessKeyId:
    description: 'AWS Access Key ID'
    required: true
  awsBucket:
    description: 'AWS Bucket name'
    required: true
  awsDynamoDBTable:
    description: 'AWS DynamoDB Table name'
    required: true
  awsRegion:
    description: 'AWS S3 Region'
    required: true
  awsSecretAccessKey:
    description: 'AWS Secret Access Key'
    required: true
  branch:
    description: 'Branch for the infrastructure'
    required: true
  clusterName:
    description: 'Cluster name'
    required: true
  environment:
    description: 'Environment for the infrastructure'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=${{ inputs.awsBucket }}" \
          -backend-config="key=${{ env.BACKEND_KEY }}" \
          -backend-config="region=${{ inputs.awsRegion }}" \
          -backend-config="dynamodb_table=${{ inputs.awsDynamoDBTable }}"
      env:
        BACKEND_KEY: "gitops-demo/${{ inputs.environment }}/${{ inputs.branch }}/cluster.tfstate"
      working-directory: terraform/cluster/${{ inputs.environment }}
      shell: bash

    - name: Terraform Destroy
      run: |
        terraform destroy \
          -auto-approve \
          -var="cluster_name=${{ inputs.clusterName }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.awsAccessKeyId }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.awsSecretAccessKey }}
      working-directory: terraform/cluster/${{ inputs.environment }}
      shell: bash