name: 'Terraform Cluster Creation'
description: 'Initialize and apply Terraform configuration for cluster creation'

inputs:
  clusterName:
    description: 'Cluster name'
    required: true

outputs:
  kubeconfigContent:
    description: 'Kubeconfig content'
    value: ${{ steps.extract_kubeconfig.outputs.kubeconfigContent }}

runs:
  using: 'composite'
  steps:
    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=${{ vars.AWS_BUCKET }}" \
          -backend-config="key=${{ env.BACKEND_KEY }}" \
          -backend-config="region=${{ vars.AWS_REGION }}" \
          -backend-config="dynamodb_table=${{ vars.AWS_DYNAMODB_TABLE }}"
      env:
        BACKEND_KEY: "gitops-demo/${{ github.environment }}/${{ github.ref_name }}/cluster.tfstate"
      working-directory: terraform/cluster-creation/${{ github.environment }}

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve -var="cluster_name=${{ inputs.clusterName }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      working-directory: terraform/cluster-creation/${{ github.environment }}

    - name: Extract Kubeconfig
      id: extract_kubeconfig
      run: echo "::set-output name=kubeconfigContent::$(terraform output -raw kubeconfig_content)"
      working-directory: terraform/cluster-creation/${{ github.environment }}