name: 'Terraform Application Destroy'
description: 'Initialize and destroy Terraform configuration for application'

inputs:
  awsAccessKeyId:
    description: 'AWS Access Key ID'
    required: true
  awsBucket:
    description: 'AWS Bucket name'
    required: true
  awsDynamoDBTable:
    description: 'AWS DynamoDB Table name'
    required: true
  awsRegion:
    description: 'AWS S3 Region'
    required: true
  awsSecretAccessKey:
    description: 'AWS Secret Access Key'
    required: true
  branch:
    description: 'Branch for the infrastructure'
    required: true
  environment:
    description: 'Environment for the infrastructure'
    required: true
  kubeconfigContent:
    description: 'Kubeconfig content'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Write Kubeconfig to file
      run: |
        echo "${{ inputs.kubeconfigContent }}" > ./kubeconfig-${{ inputs.environment }}.yaml
      shell: bash

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=${{ inputs.awsBucket }}" \
          -backend-config="key=${{ env.BACKEND_KEY }}" \
          -backend-config="region=${{ inputs.awsRegion }}" \
          -backend-config="dynamodb_table=${{ inputs.awsDynamoDBTable }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.awsAccessKeyId }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.awsSecretAccessKey }}
        BACKEND_KEY: "gitops-demo/${{ inputs.environment }}/${{ inputs.branch }}/application.tfstate"
      working-directory: terraform/applications/${{ inputs.environment }}
      shell: bash

    - name: Terraform Destroy
      run: |
        terraform destroy \
          -auto-approve \
          -var "kubeconfig_path=./kubeconfig-${{ inputs.environment }}.yaml"
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.awsAccessKeyId }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.awsSecretAccessKey }}
      working-directory: terraform/applications/${{ inputs.environment }}
      shell: bash