name: 'Terraform Application Destroy'
description: 'Initialize and destroy Terraform configuration for application'

inputs:
  kubeconfigContent:
    description: 'Kubeconfig content'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Write Kubeconfig to file
      run: |
        echo "${{ inputs.kubeconfigContent }}" > ./kubeconfig-${{ github.environment }}.yaml
      shell: bash

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=${{ vars.AWS_BUCKET }}" \
          -backend-config="key=${{ env.BACKEND_KEY }}" \
          -backend-config="region=${{ vars.AWS_REGION }}" \
          -backend-config="dynamodb_table=${{ vars.AWS_DYNAMODB_TABLE }}"
      env:
        BACKEND_KEY: "gitops-demo/${{ github.environment }}/${{ github.ref_name }}/application.tfstate"
      working-directory: terraform/application/${{ github.environment }}
      shell: bash

    - name: Terraform Destroy
      run: |
        terraform destroy \
          -auto-approve \
          -var "kubeconfig_path=./kubeconfig-${{ github.environment }}.yaml"
      env:
        AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      working-directory: terraform/application/${{ github.environment }}
      shell: bash