name: Promote Branch

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-promotion-pr:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete existing promotion branches and PRs
        run: |
          for branch in $(gh repo view --json refs --jq '.refs.nodes[] | select(.name | startswith("promote-branch-")).name'); do
            gh pr list --head "$branch" --json number --jq '.[].number' | xargs -I {} gh pr close {}
            git push origin --delete "$branch"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create promotion branch
        run: |
          MERGED_BRANCH_NAME=$(echo "${{ github.event.pull_request.head.ref }}" | sed 's/[^a-zA-Z0-9]/-/g')
          PROMOTE_BRANCH="promote-${MERGED_BRANCH_NAME}"
          echo "MERGED_BRANCH_NAME=$MERGED_BRANCH_NAME" >> $GITHUB_ENV
          echo "PROMOTE_BRANCH=$PROMOTE_BRANCH" >> $GITHUB_ENV

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b ${PROMOTE_BRANCH}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean prod directories
        run: |
          git rm -rf terraform/prod/*
          git rm -rf argocd/prod/*
          mkdir -p terraform/prod
          mkdir -p argocd/prod

      - name: Copy files from dev to prod
        run: |
          cp -r terraform/dev/* terraform/prod/
          cp -r argocd/dev/* argocd/prod/
          
      - name: Commit and push changes
        run: |
          git add terraform/prod/*
          git add argocd/prod/*
          git commit -m "Promote ${MERGED_BRANCH_NAME} to prod"
          git push origin ${PROMOTE_BRANCH}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR
        run: |
          gh pr create --title "Promote ${MERGED_BRANCH_NAME} to prod" --body "This PR promotes changes from ${MERGED_BRANCH_NAME} to prod" --base main --head ${PROMOTE_BRANCH}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}