name: Test Infrastructure

on:
  pull_request:
    branches:
      - prod
      - dev

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_wrapper: false

      - name: Find Application Directories
        run: |
          applications=$(find argocd -type f -name 'application.yaml' -exec dirname {} \; | xargs -I {} basename {})
          echo "applicationsList=[$(echo $applications | sed 's/\([^ ]*\)/"\1"/g' | sed 's/ /,/g')]" >> $GITHUB_ENV
        shell: bash

      - name: Create Infrastructure
        id: create-infrastructure
        uses: ./.github/actions/create-infrastructure
        with:
          applicationsList: ${{ env.applicationsList }}
          awsAccessKeyId: ${{ vars.AWS_ACCESS_KEY_ID }}
          awsBucket: ${{ vars.AWS_BUCKET }}
          awsDynamoDBTable: ${{ vars.AWS_DYNAMODB_TABLE }}
          awsRegion: ${{ vars.AWS_REGION }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_KEY }}
          branch: ${{ github.head_ref }}
          clusterName: ${{ vars.CLUSTER_NAME }}
          environment: ${{ vars.ENVIRONMENT_NAME }}
          repoUrl: ${{ github.repository }}
          workingDirectory: "terraform/main"

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.23.4'

      - name: Run tests
        id: run-tests
        run: |
          sleep 60
          kubectl get namespaces
        env:
          KUBECONFIG: ${{ steps.create-infrastructure.outputs.kubeconfigPath }}

      - name: Destroy Infrastructure
        if: always()
        uses: ./.github/actions/destroy-infrastructure
        with:
          applicationsList: ${{ env.applicationsList }}
          awsAccessKeyId: ${{ vars.AWS_ACCESS_KEY_ID }}
          awsBucket: ${{ vars.AWS_BUCKET }}
          awsDynamoDBTable: ${{ vars.AWS_DYNAMODB_TABLE }}
          awsRegion: ${{ vars.AWS_REGION }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_KEY }}
          branch: ${{ github.head_ref }}
          clusterName: ${{ vars.CLUSTER_NAME }}
          environment: ${{ vars.ENVIRONMENT_NAME }}
          repoUrl: ${{ github.repository }}
          workingDirectory: "terraform/main"