name: Test Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (e.g., dev, prod)'
        required: true
        type: choice
        options:
          - dev
          - prod

  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-environment.outputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment
        id: set-environment
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "::set-output name=environment::${{ github.event.inputs.environment }}"
          else
            if git diff --name-only origin/main...HEAD | grep -q 'terraform/cluster-creation/prod\|terraform/application/prod'; then
              echo "::set-output name=environment::prod"
            else
              echo "::set-output name=environment::dev"
            fi
          fi
  
  deployment:
    needs: set-environment
    runs-on: ubuntu-latest
    environment: ${{ needs.set-environment.outputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Cluster
        id: create-cluster
        uses: ./.github/actions/create-cluster.yaml
        with:
          clusterName: ${{ vars.CLUSTER_NAME }}

      - name: Create Application
        id: create-application
        uses: ./.github/actions/create-application.yaml
        with:
          kubeconfigContent: ${{ steps.create-cluster.outputs.kubeconfigContent }}

      - name: Run tests
        id: run-tests
        run: kubectl get pods -n default
        env:
          KUBECONFIG: ${{ steps.create-cluster.outputs.kubeconfigContent }}

      - name: Destroy Application
        if: always()
        uses: ./.github/actions/destroy-application.yaml
        with:
          kubeconfigContent: ${{ steps.create-cluster.outputs.kubeconfigContent }}

      - name: Destroy Cluster
        if: always()
        uses: ./.github/actions/destroy-cluster.yaml
        with:
          clusterName: ${{ vars.CLUSTER_NAME }}
