name: Test Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (e.g., dev, prod)'
        required: true
        type: choice
        options:
          - dev
          - prod

  pull_request:
    branches:
      - main
    paths:
      - 'argocd/**'
      - 'terraform/**'

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-environment.outputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set environment
        id: set-environment
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "environment=${{ inputs.environment }}" >> $GITHUB_OUTPUT
          else
            if git diff --name-only origin/main...HEAD | grep -q 'terraform/cluster-creation/prod\|terraform/application/prod'; then
              echo "environment=prod" >> $GITHUB_OUTPUT
            else
              echo "environment=dev" >> $GITHUB_OUTPUT
            fi
            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          fi
  
  deployment:
    needs: set-environment
    runs-on: ubuntu-latest
    environment: ${{ needs.set-environment.outputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_wrapper: false

      - name: Find Application Directories
        run: |
          applications=$(find argocd/${{ vars.ENVIRONMENT_NAME }} -type f -name 'application.yaml' -exec dirname {} \; | xargs -I {} basename {})
          echo "applicationsList=[$(echo $applications | sed 's/\([^ ]*\)/"\1"/g' | sed 's/ /,/g')]" >> $GITHUB_ENV
        shell: bash

      - name: Create Infrastructure
        id: create-infrastructure
        uses: ./.github/actions/create-infrastructure
        with:
          applicationsList: ${{ env.applicationsList }}
          awsAccessKeyId: ${{ vars.AWS_ACCESS_KEY_ID }}
          awsBucket: ${{ vars.AWS_BUCKET }}
          awsDynamoDBTable: ${{ vars.AWS_DYNAMODB_TABLE }}
          awsRegion: ${{ vars.AWS_REGION }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_KEY }}
          branch: ${{ needs.set-environment.outputs.branch }}
          clusterName: ${{ vars.CLUSTER_NAME }}
          environment: ${{ vars.ENVIRONMENT_NAME }}
          repoUrl: ${{ github.repository }}
          workingDirectory: "terraform/${{ vars.ENVIRONMENT_NAME }}/main"

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.23.4'

      - name: Run tests
        id: run-tests
        run: |
          sleep 60
          kubectl get namespaces
        env:
          KUBECONFIG: ${{ steps.create-infrastructure.outputs.kubeconfigPath }}

      - name: Destroy Infrastructure
        if: always()
        uses: ./.github/actions/destroy-infrastructure
        with:
          applicationsList: ${{ env.applicationsList }}
          awsAccessKeyId: ${{ vars.AWS_ACCESS_KEY_ID }}
          awsBucket: ${{ vars.AWS_BUCKET }}
          awsDynamoDBTable: ${{ vars.AWS_DYNAMODB_TABLE }}
          awsRegion: ${{ vars.AWS_REGION }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_KEY }}
          branch: ${{ needs.set-environment.outputs.branch }}
          clusterName: ${{ vars.CLUSTER_NAME }}
          environment: ${{ vars.ENVIRONMENT_NAME }}
          repoUrl: ${{ github.repository }}
          workingDirectory: "terraform/${{ vars.ENVIRONMENT_NAME }}/main"